version: 2
jobs:
  build:
    working_directory: ~/twitter
    docker:
      - image: clojure
    steps:
      - checkout
      - restore_cache:
          key: {{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: {{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/twitter.jar
          destination: uberjar
